apiVersion: 1

datasources:
  # ── Prometheus (Metrics) ────────────────────────────────────────────────────
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus_ds
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations: []
    editable: false

  # ── Loki (Logs) ─────────────────────────────────────────────────────────────
  - name: Loki
    type: loki
    access: proxy
    uid: loki_ds
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: prometheus_ds
          matcherRegex: "traceId=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
