# ── Server ──────────────────────────────────────────
server.port=8080

# ── PostgreSQL Neon Tech ─────────────────────────────
spring.datasource.url=jdbc:postgresql://ep-hidden-heart-aqv8rp6w-pooler.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_PlEGfbr4R5WT&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PlEGfbr4R5WT
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── JWT ──────────────────────────────────────────────
jwt.secret=770864096025a19b80a33e4c2d5a345678912345678912345678912345678912
jwt.expiration=86400000